### PR TITLE
Debian support

### PR DESCRIPTION
**Pull request by spinal84**
* Add Debian suites
* Fixes and improvements

This is based on reprepro-fixes branch.

### CODE REVIEW

**Comment by parazyd** [comment]
Seems ok. Let me first test the `Suite` header changes and if everything is ok I'll merge this.

**Comment by parazyd** [comment]
Thanks!

**Comment by MerlijnWajer** [comment]
```
root@devuan:~/brainparty# apt update
Get:1 http://maedevu.maemo.org/leste beowulf InRelease [26.3 kB]
E: Repository 'http://maedevu.maemo.org/leste beowulf InRelease' changed its 'Origin' value from 'Devuan' to 'Maemo Leste'
E: Repository 'http://maedevu.maemo.org/leste beowulf InRelease' changed its 'Label' value from 'Devuan-All' to 'Maemo Leste'
N: Repository 'http://maedevu.maemo.org/leste beowulf InRelease' changed its 'Version' value from '1.0' to ''
E: Repository 'http://maedevu.maemo.org/leste beowulf InRelease' changed its 'Suite' value from 'bayamo' to 'unstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N]
```

**Comment by MerlijnWajer** [comment]
Might not be a problem, but hey. Might confuse some users.

**Comment by spinal84** [comment]
It may be a good idea to make a note about this in monthly update.
But for me, it seems minor, the warning message is pretty clear.

**Pull request merged**
