### PR TITLE
Reprepro fixes

### PR DESCRIPTION
**Pull request by spinal84**
Misc fixes to reprepro configuration files

### CODE REVIEW

**Comment by parazyd** [comment]
This will not work for the time being. I will consider this at a later point.

**Comment by parazyd** [comment]
To explain a bit:

We can _try_ changing `Origin` and `Label`, however changing `Suite` is going to break the jenkins-debian-glue and how it works. In its `build-and-provide-package` it does a number of grep calls to figure out where it should place the packages in the end, and since the build process is quite dependent on the initial two variables we put in the beginning (`-sources` job), I would advise we don't change this.

**Comment by spinal84** [comment]
> To explain a bit:
> 
> We can _try_ changing `Origin` and `Label`, however changing `Suite` is going to break the jenkins-debian-glue and how it works. In its `build-and-provide-package` it does a number of grep calls to figure out where it should place the packages in the end, and since the build process is quite dependent on the initial two variables we put in the beginning (`-sources` job), I would advise we don't change this.

I didn't find any entries considering "suite" in `build-and-provide-package`. What exactly did you mean?

**Comment by spinal84** [comment]
As far as I can see it takes ${RELEASE_REPOSITORY} directory and places the built package there using the value taken from ${distribution} variable. These variables are read from /etc/debian_glue.
What am I missing?

**Comment by parazyd** [comment]
Closing this since it's part of PR#12

**Pull request closed without merging**
